language: c
sudo: true
notifications:
  email: false
before_install:
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update; else brew update; fi;
after_success:
    - bash <(curl -s https://codecov.io/bash)
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8
    - gcc-7
    - gcc-4.8
    - valgrind
    # - clang-6.0
    # - clang-5.0
matrix:
    include:
        - os: osx
          compiler: gcc
          env: CXX=gcc
        - os: osx
          compiler: clang
          env: CXX=clang
        - os: linux
          compiler: gcc-8
          env: CXX=gcc-8
        - os: linux
          compiler: gcc-7
          env: CXX=gcc-7
        - os: linux
          compiler: gcc-4.8
          env: CXX=gcc-4.8
        - os: linux
          compiler: clang
          env: CXX=clang
        # - os: linux
        #   compiler: clang-6.0
        #   env: CXX=clang-6.0
        # - os: linux
        #   compiler: clang-5.0
        #   env: CXX=clang-5.0
    allow_failures:
        - os: linux
          compiler: gcc-7
          env: CXX=gcc-7
        - os: linux
          compiler: gcc-4.8
          env: CXX=gcc-4.8
        - os: linux
          compiler: clang
          env: CXX=clang
        # - os: linux
        #   compiler: clang-6.0
        #   env: CXX=clang-6.0
        # - os: linux
        #   compiler: clang-5.0
        #   env: CXX=clang-5.0
script: make CC=$CXX verbose && make CC=$CXX tests && ./tests/launch_tests.sh; r=$? make coverage; return $r;
