language: c
sudo: true
notifications:
  email: false
before_install:
    - brew update || sudo apt-get update -yqq
after_success:
    - bash <(curl -s https://codecov.io/bash)
matrix:
    include:
        - os: osx
          compiler: gcc
          env: CXX=gcc
        - os: osx
          compiler: clang
          env: CXX=clang
        - os: linux
          compiler: gcc
          env: CXX=gcc
        - os: linux
          compiler: clang
          env: CXX=clang
    allow_failures:
        - os: linux
          compiler: gcc
          env: CXX=gcc
        - os: linux
          compiler: clang
          env: CXX=clang
script: make tests && ./21sh_tests; r=$?; make coverage; return $r
