language: c
sudo: true
notifications:
  email: false
before_install:
    - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get update; else brew update; fi
after_success:
    - bash <(curl -s https://codecov.io/bash)
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - gcc-7
    - valgrind
matrix:
    include:
        - os: osx
          compiler: gcc
          env: CXX=gcc
        - os: osx
          compiler: clang
          env: CXX=clang
        - os: linux
          compiler: gcc-7
          env: CXX=gcc-7
        - os: linux
          compiler: gcc-4.8
          env: CXX=gcc-4.8
        - os: linux
          compiler: clang
          env: CXX=clang
    allow_failures:
        - os: linux
          compiler: gcc-7
          env: CXX=gcc-7
        - os: linux
          compiler: gcc-4.8
          env: CXX=gcc-4.8
        - os: linux
          compiler: clang
          env: CXX=clang
script: make CC=$CXX tests && ./21sh_tests; r=$?; make coverage; return $r
